pipeline {
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'Terraform', url: 'https://github.com/girish-kin/TestSample.git'
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                sh '''
                    cd project_1
                    terraform init
                    terraform plan -out=tfplan
                    terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                    cd project_1
                    terraform apply -auto-approve
                '''
            }
        }
    }
}
